import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Header = () => {
  return (
    <header className="bg-gray-800 text-white py-4">
      <div className="container mx-auto">
        <nav className="flex justify-between items-center">
          <div className="flex gap-5 items-center">
            <Link className="hover:text-gray-300 transition-colors duration-300 cursor-pointer text-xl font-semibold" href="/">
              Super Avaliador 3000
            </Link>
          </div>
          <div>
            <Link
              className="text-white hover:text-gray-300 transition-colors duration-300 cursor-pointer mr-10"
              href="/newAvaliadores"
            >
              Cadastrar avaliador
            </Link>
            <Link href="/newEquipes">Cadastrar Equipe</Link>
          </div>
        </nav>
      </div>
    </header>
  )
}

const Footer = () => {
  return (
    <footer className="bg-gray-800 text-white py-4">
      <div className="container mx-auto text-center">
        <p>Trabalho de Fernando Dreyer Radünz - Todos os direitos reservados</p>
      </div>
    </footer>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <Header />
        <main className="flex-grow">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
